services:
  zookeeper:
    image: zookeeper
    container_name: zookeeper
    hostname: zookeeper
    networks: [ opensearch-net ]
    volumes:
      - zk-logs:/logs
      - zk-data:/data
      - zk-datalog:/datalog

  nimbus:
    image: storm:2.6-jre17
    container_name: nimbus
    hostname: nimbus
    networks: [ opensearch-net ]
    ports: [ 6627:6627 ]
    depends_on: [ zookeeper ]
    volumes: [ storm-nimbus-logs:/logs ]
    command: storm nimbus

  supervisor:
    image: storm:2.6-jre17
    container_name: supervisor
    hostname: supervisor
    networks: [ opensearch-net ]
    ports: [ 6700:6700 ]
    depends_on: [ nimbus, zookeeper ]
    volumes: [ storm-supervisor-logs:/logs ]
    command: storm supervisor -c worker.childopts=-Xmx%HEAP-MEM%m

  ui:
    image: storm:2.6-jre17
    container_name: ui
    hostname: ui
    networks: [ opensearch-net ]
    ports: [ "127.0.0.1:8080:8080" ]
    depends_on: [ nimbus ]
    volumes: [ storm-ui-logs:/logs ]
    command: storm ui

  # runner:
  #   build:
  #     dockerfile_inline: |
  #       FROM storm:2.6
  #       ENV JAVA_HOME=/usr/lib/jvm/default-java
  #       RUN apt update; \
  #           apt install -y maven software-properties-common; \
  #           apt autoremove && apt clean;
  #       # alias mvn="mvn -Dmaven.repo.local=/crawldata/.repository"
  #       USER storm
  #       COPY ./storm.test.yaml /conf/storm.yaml
  #   image: jhs88/storm_crawler
  #   container_name: runner
  #   networks: [ opensearch-net ]
  #   depends_on: [ nimbus ]
  #   volumes: [ ./:/crawldata]
  #   command: sleep infinity 

  opensearch-node1:
    image: opensearchproject/opensearch:2.17.1
    container_name: opensearch-node1
    hostname: opensearch-node1
    networks: [ opensearch-net ]
    ports:
      - 9200:9200 # REST API
      - 9600:9600 # Performance Analyzer
    environment:
      - cluster.name=${CLUSTER_NAME:-opensearch-cluster} # Name the cluster
      - node.name=opensearch-node1 # Name the node that will run in this container
      - discovery.seed_hosts=${DISCOVERY_SEED_HOSTS:-opensearch-node1} # Nodes to look for when discovering the cluster
      - cluster.initial_cluster_manager_nodes=${DISCOVERY_SEED_HOSTS:-opensearch-node1} # Nodes eligible to serve as cluster manager
      - bootstrap.memory_lock=true # Disable JVM heap memory swapping
      - "OPENSEARCH_JAVA_OPTS=-Xms512m -Xmx512m" # Set min and max JVM heap sizes to at least 50% of system RAM
      # - OPENSEARCH_INITIAL_ADMIN_PASSWORD=${OPENSEARCH_INITIAL_ADMIN_PASSWORD}    # Sets the demo admin user password when using demo configuration, required for OpenSearch 2.12 and later
      - DISABLE_INSTALL_DEMO_CONFIG=true
      - DISABLE_SECURITY_PLUGIN=true
    ulimits:
      memlock:
        soft: -1 # Set memlock to unlimited (no soft or hard limit)
        hard: -1
      nofile:
        soft: 65536 # Maximum number of open files for the opensearch user - set to at least 65536
        hard: 65536
    volumes: [ "opensearch-data1:${OPENSEARCH_HOME:-/usr/share/opensearch}" ]
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "5"

  opensearch-dashboards:
    image: opensearchproject/opensearch-dashboards:2.17.0
    container_name: opensearch-dashboards
    hostname: opensearch-dashboards
    networks: [ opensearch-net ]
    ports: [ 5601:5601 ]
    environment:
      OPENSEARCH_HOSTS: '["http://opensearch-node1:9200"]'
      DISABLE_SECURITY_DASHBOARDS_PLUGIN: true

volumes:
  opensearch-data1:
  storm-ui-logs:
  storm-nimbus-logs:
  storm-supervisor-logs:
  zk-logs:
  zk-data:
  zk-datalog:

networks:
  opensearch-net:
